version: '2.2'
services:
  elasticsearch:
    # build: .
    image: elasticsearch:2.4.3
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local